In [1]:
# Import thư viện numpy
import numpy as np

## Tạo Numpy Arrays từ Python Lists

In [2]:
# Chuyển đổi từ pythonlist sang numpy array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4])

In [3]:
# python list có thể chứa mảng khác kiểu dữ liệu
[1, 3.4, 5.3, 2]

[1, 3.4, 5.3, 2]

In [4]:
# numpy chuyển đổi các item thành số thực
np.array([1, 3.4, 5.3, 2])

array([1. , 3.4, 5.3, 2. ])

In [5]:
# Có thể chuyển đổi ví dụ số nguyên thành số thực 32bit
np.array([1, 2, 3, 4, 5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
# Gán np.array cho một biến
c = np.array([1, 2, 3, 4, 5])
type(c)

numpy.ndarray

In [9]:
c1 = np.array([[1, 2, 3],
                [6, 8, 9]])
type(c1)

numpy.ndarray

In [10]:
# Hàm shape hiển thị số dòng cột
c1.shape

(2, 3)

__Có 2 hàng và 3 cột__

In [11]:
# Hàm ndim kiểm tra chiều của mảng
c1.ndim # mảng 2 chiều

2

In [12]:
# Kiểu dữ liệu bên trong mảng c1
c1.dtype

dtype('int32')

In [13]:
# Tổng elements thành phần trong mảng
c1.size

6

__Không giống như danh sách Python, mảng NumPy rõ ràng có thể đa chiều__

## Tạo Numpy Arrays từ Built-in Function: Hàm có sẵn

__zeros, ones, arange, full, linspace__

In [17]:
# Hàm zeros dùng để tạo mảng toàn số 0
# Ví dụ mảng 2 hàng, 4 cột
# Kiểu dữ liệu float mặc định
np.zeros([2, 4]).dtype

dtype('float64')

In [18]:
# Thay đổi kiều dữ liệu
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
# Hàm ones dùng để tạo hàm số 1, kiểu dữ liệu được tùy chỉnh
np.ones([3,5], dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# Hàm arange
# Tạo 1 mảng với start = 0, stop = 20 và step = 2 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# Hàm full
np.full((3, 5), 16.2)

array([[16.2, 16.2, 16.2, 16.2, 16.2],
       [16.2, 16.2, 16.2, 16.2, 16.2],
       [16.2, 16.2, 16.2, 16.2, 16.2]])

In [25]:
# Hàm linspace
# Một mảng năm giá trị cách đều nhau từ 0 đến 1
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.linspace()

## random

In [26]:
# Hàm random chỉ nhaanjn input là size
np.random.random((4, 4))

array([[0.39167989, 0.49298903, 0.35218427, 0.76528629],
       [0.94201464, 0.98637707, 0.59876075, 0.75369665],
       [0.01693656, 0.9457357 , 0.72396703, 0.78977217],
       [0.56072983, 0.93120254, 0.04259156, 0.62468175]])

In [32]:
# Hàm seed() hức được sử dụng để khởi tạo trình tạo số ngẫu nhiên.
# Trình tạo số ngẫu nhiên cần một số bắt đầu bằng (giá trị gốc) để có thể tạo một số ngẫu nhiên.
np.random.seed(0)
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [33]:
# normal
# Vẽ các mẫu ngẫu nhiên từ phân phối chuẩn (Gaussian).
# theo thứ tự mean: giá trị trung bình, std - Standard Deviation: độ lệch chuẩn
# size ma trận 3x3
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [34]:
# randint() random những số int
np.random.randint(0, 10, (4, 5)) 

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [35]:
# Hàm rand
np.random.randn(4, 4)

array([[-0.74216502, -1.02617878,  0.47752547,  1.29269823],
       [-0.73145824, -1.60540226,  0.98947618,  0.11081461],
       [-0.38093141,  0.11495917,  0.34531264, -1.73495876],
       [ 1.65835111,  2.29977152, -0.47113526,  1.26271548]])

## Array Indexing & Slicing

__Mảng con một chiều__

In [36]:
x1 = np.random.randint(20, size = 6) # Mảng một chiều

In [37]:
x1

array([16, 17,  5,  9,  3,  0])

In [41]:
x1[4], x1[0], x1[-1]

(3, 16, 0)

__Mảng đa chiều__

In [43]:
# Ma trận là đoạn từ 0 đến 10
x2 = np.random.randint(10, size=(3, 4)) # Mảng hai chiều 

In [44]:
x2

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [45]:
# index đầu tiên = hàng, index thứ 2 = cột
x2[1, 2]

0

In [46]:
# Thay đổi số trong ma trận bằng cách gán
x2[1, 2] = 66

In [47]:
x2

array([[ 5,  0,  1,  2],
       [ 4,  2, 66,  3],
       [ 2,  0,  7,  5]])

__Slicing__

`x[start:stop:step]`

In [48]:
x1

array([16, 17,  5,  9,  3,  0])

In [49]:
# Lấy 3 giá trị đầu tiên
x1[0:3]

array([16, 17,  5])

In [50]:
# Lấy ở vị trí thứ 2 và dừng ở vị trí thứ 4
x1[2:4]

array([5, 9])

In [51]:
# mỗi step cách nhau 2
x1[::2]

array([16,  5,  3])

In [52]:
x2

array([[ 5,  0,  1,  2],
       [ 4,  2, 66,  3],
       [ 2,  0,  7,  5]])

In [54]:
# Láy 2 hàng đầu và 3 cột đầu
x2[:2, :3]

array([[ 5,  0,  1],
       [ 4,  2, 66]])

In [57]:
# Lấy 2 dòng đầu tiên
x2[:, :2]

array([[5, 0],
       [4, 2],
       [2, 0]])

## Reshape và Transpose

In [58]:
# Tạo 1 mảng trong đoạn từ 1 đến 10
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# gán biến grown cho mảng vừa tạo
grown = np.arange(1, 10)

# Một numpy array có 9 hàng
grown.shape

(9,)

In [61]:
# Hàm reshape() tạo ma trận 3x3
grown.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [63]:
# Có 1 row và 3 columns
x.reshape(1, 3).shape

(1, 3)

In [65]:
# Transpose sẽ chuyển đổi cột thành hàng và hàng thành cột
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [66]:
# Chuyển đổi hàng thành cột
x.T

array([[1, 3],
       [2, 4]])

## Concatenation và Splitting

`Concatenation: nối các numpy array lại với nhau`

`Splitting: Tách những numpy array ra thành các array nhỏ hơn`

In [68]:
# Mảng 1 chiều 
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [72]:
# Nối 2 array lại với nhau
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [74]:
# Mảng 2 chiều
grid = np.array([[1, 2, 3],
               [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
# Nối theo hàng
np.concatenate([grid, grid]) #axis = 0 mặc định nối theo chiều ngang

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
# Nối theo cột
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
#vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# Nối theo cột
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [78]:
# horizontally stack - Nối theo chiều ngang
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

__Splitting__

In [79]:
x = [1, 2, 3, 99, 69, 3, 2, 1]

In [80]:
# Tách ra 3 array khác nhau
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
